title: Ryan Quach
description: M.S. Statistics | Data Science | Research
theme: minima

minima:
  skin: auto

show_downloads: false
google_analytics:  # optional
author: Ryan Quach
github:
  is_project_page: false

# Optional social media
social_links:
  linkedin: https://www.linkedin.com/in/ryan-quach/
  github: https://github.com/ryanquach03
  email: ryanquach03@g.ucla.edu

header_pages:
  - index.md
  - projects.md
