title: My Portfolio
author: Ryan Quach
description: M.S. Statistics | Data Science | Research
theme: minima

minima:
  skin: auto

show_downloads: false
google_analytics:  # optional
github:
  is_project_page: false

social:
  linkedin: https://www.linkedin.com/in/ryan-quach/
  github: https://github.com/ryanquach03
  email: mailto:ryanquach03@g.ucla.edu

header_pages:
  - about.md
  - experience.md
  - projects.md
